import io.micronaut.build.internal.generator.BeanGeneratorTask;

plugins {
    id("io.micronaut.build.internal.json-schema-base")
}

repositories {
    mavenCentral()
}

configurations {
    beanGenerator {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    beanGenerator(project(":micronaut-json-schema-generator"))
}

def beanGenerator = tasks.register("generateBean", BeanGeneratorTask) {
    language = "java"
    classpath.from(configurations.beanGenerator)
    jsonFile.convention(layout.projectDirectory.file("src/test/resources/animal.schema.json"))
    outputDirectory.convention(layout.buildDirectory.dir("generated/jsonSchema"))
    packageName.convention("io.micronaut.jsonschema.generator.animals")
}

def beanGenerator2 = tasks.register("generateBean2", BeanGeneratorTask) {
    language = "java"
    classpath.from(configurations.beanGenerator)
    jsonFile.convention(layout.projectDirectory.file("src/test/resources/llama.schema.json"))
    outputDirectory.convention(layout.buildDirectory.dir("generated/jsonSchema"))
    packageName.convention("io.micronaut.jsonschema.generator.llama")
}

sourceSets {
    main {
        java.srcDir(beanGenerator.map(BeanGeneratorTask::getGeneratedSourcesDirectory))
        java.srcDir(beanGenerator2.map(BeanGeneratorTask::getGeneratedSourcesDirectory))
    }
}

dependencies {
    constraints {
    }
}
