pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'io.micronaut.build.shared.settings' version '8.0.0-M18'
}

dependencyResolutionManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

enableFeaturePreview 'TYPESAFE_PROJECT_ACCESSORS'

rootProject.name = 'json-schema-parent'

include 'json-schema-validation'
include 'json-schema-bom'
include 'json-schema-annotations'
include 'json-schema-common'
include 'json-schema-processor'
include 'json-schema-generator'
include 'json-schema-registry'
include 'json-schema-utils'
include 'json-schema-configuration-validator'
include 'test-suite'
include 'test-suite-generator-java'
include 'test-suite-groovy'
include 'test-suite-kotlin'

enableFeaturePreview 'TYPESAFE_PROJECT_ACCESSORS'

micronautBuild {
    useStandardizedProjectNames = true
    importMicronautCatalog()
    importMicronautCatalog('micronaut-validation')
    importMicronautCatalog('micronaut-serde')
    importMicronautCatalog('micronaut-sourcegen')
    importMicronautCatalog('micronaut-sql')
    importMicronautCatalog('micronaut-testresources')
    importMicronautCatalog("micronaut-micrometer")
}
