plugins {
    id("io.micronaut.build.internal.json-schema-module")
}

micronautBuild {
    binaryCompatibility {
        enabledAfter("1.4.0")
    }
}

dependencies {
    api(mn.jackson.databind)

    testImplementation(mn.micronaut.inject.groovy.test)
    testImplementation(mn.micronaut.inject.java.test)
    testImplementation(mnLogging.logback.classic)
    testImplementation(mnLogging.logback.core)
    testImplementation(mnLogging.slf4j.api)
    testImplementation(mnLogging.slf4j.simple)
}


test {
    useJUnitPlatform()
}
