plugins {
    id("java-library")
    id("groovy")
}

dependencies {
    testImplementation(mnValidation.validation)
    testImplementation(projects.micronautJsonSchemaAnnotations)
    testImplementation(mnSerde.micronaut.serde.jackson)

    testAnnotationProcessor(projects.micronautJsonSchemaProcessor)
    testAnnotationProcessor(mnSerde.micronaut.serde.processor)
    testAnnotationProcessor(mn.micronaut.inject.java)

    testImplementation(mn.jackson.databind)

    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(mn.micronaut.http.client)
    testImplementation(projects.micronautJsonSchemaValidation)
    testImplementation(mn.micronaut.inject.kotlin.test)
    testImplementation(mn.micronaut.inject.groovy.test)
    testImplementation(mn.micronaut.inject.java.test)
    testImplementation(mn.micronaut.inject)

    testImplementation(mnTest.micronaut.test.spock)
    testImplementation(mnTest.micronaut.test.junit5)
    testImplementation(mnTest.junit.jupiter.api)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
    testImplementation(mnTest.junit.jupiter.params)
    testRuntimeOnly(mnTest.junit.platform.launcher)
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.add("-Amicronaut.jsonschema.baseUri=https://example.com/schemas")
}
test {
    useJUnitPlatform()
}
