plugins {
    id("java-gradle-plugin")
    id("io.micronaut.build.internal.json-schema-module")
}

dependencies {
    implementation(projects.micronautJsonSchemaGenerator)
    compileOnly(libs.micronaut.build.plugin.sourcegen.annotations)
    annotationProcessor(libs.micronaut.build.plugin.sourcegen.generator)
    annotationProcessor(projects.micronautJsonSchemaGenerator)
    annotationProcessor(libs.javaparser.core.sourcegen) {
        version {
            strictly(libs.versions.javaparser.sourcegen.get())
        }
    }
    annotationProcessor(libs.javaparser.symbol.solver.sourcegen) {
        version {
            strictly(libs.versions.javaparser.sourcegen.get())
        }
    }
    testImplementation(gradleTestKit())
    testImplementation(mnTest.junit.jupiter.api)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
    testRuntimeOnly(mnTest.junit.platform.launcher)
}

gradlePlugin {
    plugins {
        jsonSchemaRecords {
            id = "io.micronaut.jsonschema.records"
            implementationClass = "io.micronaut.jsonschema.gradle.JsonSchemaRecordsGradlePlugin"
        }
    }
}

micronautBuild {
    descriptor {
        parentModuleId = "io.micronaut.jsonschema:micronaut-json-schema-gradle-plugin"
    }
}

configurations.named("annotationProcessor") {
    resolutionStrategy.force(
        "io.micronaut:micronaut-core:5.0.0-M8",
        "io.micronaut:micronaut-inject:5.0.0-M8",
        "io.micronaut:micronaut-core-processor:5.0.0-M8",
        "io.micronaut:micronaut-inject-java:5.0.0-M8",
        "io.micronaut.sourcegen:micronaut-sourcegen-annotations:1.8.4",
        "io.micronaut.sourcegen:micronaut-sourcegen-model:1.8.4",
        "io.micronaut.sourcegen:micronaut-sourcegen-generator:1.8.4",
        "io.micronaut.sourcegen:micronaut-sourcegen-generator-java:1.8.4",
        "com.github.javaparser:javaparser-core:3.27.1",
        "com.github.javaparser:javaparser-symbol-solver-core:3.27.1"
    )
}
