/*
 * Copyright 2017-2025 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.jsonschema.utils;

import io.micronaut.core.io.Readable;
import io.micronaut.core.io.ResourceLoader;
import io.micronaut.core.io.scan.ClassPathResourceLoader;
import org.jspecify.annotations.NonNull;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * API to retrieve a JSON Schema for a class.
 * @since 1.7.0
 */
public interface JsonSchemaClassPathResourceLoader {

    /**
     * Create a default {@link JsonSchemaClassPathResourceLoader} for the given {@link ClassLoader}.
     *
     * <p>This factory is intended for usage outside of the Micronaut DI framework (for example, CLI tools).
     * It composes the built-in schema loaders that are normally registered as beans.</p>
     *
     * @param classLoader The classloader
     * @return The default loader
     * @since 2.1.0
     */
    @NonNull
    static JsonSchemaClassPathResourceLoader createDefault(@NonNull ClassLoader classLoader) {
        Objects.requireNonNull(classLoader, "classLoader");

        ResourceLoader resourceLoader = ClassPathResourceLoader.defaultLoader(classLoader);
        JsonSchemaClassPathResourceLoader configurationLoader = new ConfigurationJsonSchemaClassPathResourceLoader(resourceLoader);
        JsonSchemaConfiguration jsonSchemaConfiguration = new JsonSchemaConfiguration() {
        };
        JsonSchemaClassPathResourceLoader generatedLoader = new DefaultJsonSchemaClassPathResourceLoader(resourceLoader, jsonSchemaConfiguration);

        return createComposite(configurationLoader, generatedLoader);
    }

    /**
     * Create a {@link JsonSchemaClassPathResourceLoader} that loads only Micronaut configuration schemas
     * ({@code META-INF/micronaut-configuration-schemas/}).
     *
     * @param classLoader The classloader
     * @return The loader
     * @since 2.1.0
     */
    @NonNull
    static JsonSchemaClassPathResourceLoader createConfigurationSchemasLoader(@NonNull ClassLoader classLoader) {
        Objects.requireNonNull(classLoader, "classLoader");
        ResourceLoader resourceLoader = ClassPathResourceLoader.defaultLoader(classLoader);
        return new ConfigurationJsonSchemaClassPathResourceLoader(resourceLoader);
    }

    /**
     * Create a {@link JsonSchemaClassPathResourceLoader} that loads schemas generated by the Micronaut
     * JSON Schema annotation processor ({@code META-INF/<outputLocation>/}).
     *
     * @param classLoader The classloader
     * @return The loader
     * @since 2.1.0
     */
    @NonNull
    static JsonSchemaClassPathResourceLoader createGeneratedSchemasLoader(@NonNull ClassLoader classLoader) {
        Objects.requireNonNull(classLoader, "classLoader");
        ResourceLoader resourceLoader = ClassPathResourceLoader.defaultLoader(classLoader);
        JsonSchemaConfiguration jsonSchemaConfiguration = new JsonSchemaConfiguration() {
        };
        return new DefaultJsonSchemaClassPathResourceLoader(resourceLoader, jsonSchemaConfiguration);
    }

    /**
     * Compose multiple non-empty loaders into one.
     */
    @NonNull
    private static JsonSchemaClassPathResourceLoader createComposite(@NonNull JsonSchemaClassPathResourceLoader... loaders) {
        Objects.requireNonNull(loaders, "loaders");

        return new JsonSchemaClassPathResourceLoader() {
            @Override
            public <T> Optional<String> jsonSchemaStringForClass(@NonNull Class<T> type) {
                for (JsonSchemaClassPathResourceLoader loader : loaders) {
                    if (loader == null) {
                        continue;
                    }
                    Optional<String> schema = loader.jsonSchemaStringForClass(type);
                    if (schema.isPresent()) {
                        return schema;
                    }
                }
                return Optional.empty();
            }

            @Override
            @NonNull
            public Map<String, Readable> jsonSchemas() {
                Map<String, Readable> schemas = new LinkedHashMap<>();
                for (JsonSchemaClassPathResourceLoader loader : loaders) {
                    if (loader == null) {
                        continue;
                    }
                    loader.jsonSchemas().forEach(schemas::putIfAbsent);
                }
                return schemas;
            }
        };
    }

    /**
     * This method retrieves the JSON Schema for a class for which a JSON Schema was generated.
     * Micronaut JSON Schema annotation processor generates a JSON Schema at compilation-time for classes annotated with {@link io.micronaut.jsonschema.JsonSchema}.
     * The generated JSON Schema, by default, is saved to META/schemas.
     * @param type the class for which a JSON Schema was generated at compilation-time.
     * @return A JSON Schema
     * @param <T> Type used to generate the JSON Schema
     */
    <T> Optional<String> jsonSchemaStringForClass(@NonNull Class<T> type);

    /**
     * @return A map of all available JSON schemas keyed by their location within the schema folder.
     *
     * <p>For example, for schemas generated by the Micronaut JSON Schema annotation processor the
     * keys are paths relative to {@code META-INF/<outputLocation>/} (e.g. {@code product.schema.json}).</p>
     *
     * <p>Implementations may return an empty map if bulk discovery is not supported for the
     * underlying {@link io.micronaut.core.io.ResourceLoader}.</p>
     *
     * @since 2.0.0
     */
    @NonNull
    default Map<String, Readable> jsonSchemas() {
        return Map.of();
    }
}
