plugins {
    id("io.micronaut.build.internal.json-schema-module")
}

dependencies {
    compileOnly(mn.micronaut.core.processor)

    implementation(projects.micronautJsonSchemaAnnotations)
    implementation(mn.micronaut.http)
    implementation(mn.micronaut.http.client)
    implementation(mn.micronaut.jackson.databind)
    implementation(mnSerde.micronaut.serde.jackson)
    implementation(mnValidation.validation)

    annotationProcessor(mn.micronaut.http.validation)
    annotationProcessor(mnSerde.micronaut.serde.processor)

    testAnnotationProcessor(mn.micronaut.inject.java)
    testImplementation(mn.micronaut.inject)
    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(mnTest.micronaut.test.junit5)
    testImplementation(libs.junit.jupiter.api)
    testRuntimeOnly(libs.junit.jupiter.engine)
}


tasks.test {
    useJUnitPlatform()
}

sourceSets {
    test {
        java.srcDir('src/test/java')
    }
}
