plugins {
    id("io.micronaut.build.internal.json-schema-module")
}

dependencies {
    compileOnly(mn.micronaut.core.processor)
    implementation(mn.micronaut.http)
    implementation(mn.micronaut.http.client)
    api(mn.micronaut.inject)

    testAnnotationProcessor(mn.micronaut.inject.java)
    testImplementation(mn.micronaut.inject)
    testImplementation(mn.micronaut.jackson.databind)
    testImplementation(mnValidation.validation)
    testImplementation(mnTest.micronaut.test.junit5)
    testImplementation(libs.junit.jupiter.api)
    testRuntimeOnly(libs.junit.jupiter.engine)
}


tasks.test {
    useJUnitPlatform()
}

sourceSets {
    test {
        java.srcDir('src/test/java')
    }
}
