/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.jsonschema.configuration.validator.report;

import io.micronaut.jsonschema.configuration.validator.ConfigurationError;
import org.jspecify.annotations.NonNull;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.util.Set;

/**
 * Reports errors as an HTML document.
 */
public final class HtmlConfigurationErrorReporter implements ConfigurationErrorReporter {
    private final OutputStream output;

    /**
     * @param output The output stream
     */
    public HtmlConfigurationErrorReporter(@NonNull OutputStream output) {
        this.output = output;
    }

    @Override
    public void report(Set<ConfigurationError> errors) throws IOException {
        long errorCount = errors.stream().filter(e -> e.type() == ConfigurationError.Type.ERROR).count();
        long warningCount = errors.stream().filter(e -> e.type() == ConfigurationError.Type.WARNING).count();

        StringBuilder html = new StringBuilder(8192);
        html.append("<!doctype html><html lang='en'><head><meta charset='utf-8'>")
            .append("<meta name='viewport' content='width=device-width, initial-scale=1'>")
            .append("<title>Configuration validation errors</title>")
            .append("<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css'>")
            .append("<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css'>")
            .append("<style>")
            // Fallback styles if CDN fails
            .append("body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;}")
            .append("code{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace;}")
            .append(".mn-hero{background:linear-gradient(135deg,#101828,#2a2d3e);color:#fff;}")
            .append(".mn-hero img{height:28px;}")
            .append(".mn-kv{opacity:.9;font-size:.95rem;}")
            .append(".table-fixed{table-layout:fixed;}")
            .append(".col-prop{width:22%;}")
            .append(".col-type{width:8%;}")
            .append(".col-msg{width:26%;}")
            .append(".col-origin{width:18%;}")
            .append(".col-raw{width:13%;}")
            .append(".col-value{width:13%;}")
            .append(".mn-wrap{word-break:break-word;white-space:normal;}")
            .append("pre{margin:0;}")
            .append("code.hljs{padding:12px;border-radius:8px;}")
            .append("</style>")
            .append("</head><body>")
            .append("<header class='mn-hero py-4'>")
            .append("<div class='container'>")
            .append("<div class='d-flex align-items-center gap-3'>")
            .append("<img alt='Micronaut' src='https://docs.micronaut.io/latest/img/micronaut-logo-white.svg'>")
            .append("<div>")
            .append("<h1 class='h3 mb-1'>Configuration validation errors</h1>")
            .append("<div class='mn-kv'>Generated by micronaut-json-schema-configuration-validator</div>")
            .append("</div>")
            .append("</div>")
            .append("</div>")
            .append("</header>")
            .append("<main class='container my-4'>")
            .append("<div class='row g-3 mb-3'>")
            .append("<div class='col-sm-4'><div class='p-3 border rounded bg-light'>")
            .append("<div class='text-secondary small'>Total</div>")
            .append("<div class='h4 mb-0'>").append(errors.size()).append("</div>")
            .append("</div></div>")
            .append("<div class='col-sm-4'><div class='p-3 border rounded bg-light'>")
            .append("<div class='text-secondary small'>Errors</div>")
            .append("<div class='h4 mb-0 text-danger'>").append(errorCount).append("</div>")
            .append("</div></div>")
            .append("<div class='col-sm-4'><div class='p-3 border rounded bg-light'>")
            .append("<div class='text-secondary small'>Warnings</div>")
            .append("<div class='h4 mb-0 text-warning'>").append(warningCount).append("</div>")
            .append("</div></div>")
            .append("</div>");

        if (errors.isEmpty()) {
            html.append("<div class='alert alert-success' role='alert'>No configuration validation errors.</div>")
                .append("</main></body></html>");

            output.write(html.toString().getBytes(StandardCharsets.UTF_8));
            output.flush();
            return;
        }

        html.append("<div class='table-responsive'>")
            .append("<table class='table table-striped table-hover align-middle table-fixed'>")
            .append("<thead class='table-light'><tr>")
            .append("<th class='col-prop'>Property</th>")
            .append("<th class='col-type'>Type</th>")
            .append("<th class='col-msg'>Message</th>")
            .append("<th class='col-origin'>Origin</th>")
            .append("<th style='width:6%'>Line</th>")
            .append("<th class='col-raw'>Raw</th>")
            .append("<th class='col-value'>Value</th>")
            .append("<th style='width:12%'>Snippet</th>")
            .append("</tr></thead><tbody>");

        for (ConfigurationError error : errors) {
            String typeBadge = switch (error.type()) {
                case ERROR -> "<span class='badge text-bg-danger'>ERROR</span>";
                case WARNING -> "<span class='badge text-bg-warning'>WARNING</span>";
            };
            html.append("<tr>")
                .append("<td class='mn-wrap'><code>").append(escape(error.property())).append("</code></td>")
                .append("<td>").append(typeBadge).append("</td>")
                .append("<td class='mn-wrap'>").append(escape(error.message())).append("</td>")
                .append("<td class='mn-wrap'>").append(escape(error.originLocation())).append("</td>")
                .append("<td>").append(error.lineNumber()).append("</td>")
                .append("<td class='mn-wrap'><code>").append(escape(error.rawPropertyName())).append("</code></td>")
                .append("<td class='mn-wrap'><code>").append(escape(error.rawValue() != null ? String.valueOf(error.rawValue()) : null)).append("</code></td>");

            String snippet = error.snippet();
            if (snippet != null && !snippet.isBlank()) {
                String language = error.snippetLanguage() != null ? error.snippetLanguage() : "plaintext";
                html.append("<td>")
                    .append("<details>")
                    .append("<summary>View</summary>")
                    .append("<div class='mt-2'>")
                    .append("<pre><code class='hljs language-").append(escape(language)).append("'>")
                    .append(escape(snippet))
                    .append("</code></pre>")
                    .append("</div>")
                    .append("</details>")
                    .append("</td>");
            } else {
                html.append("<td class='text-secondary'>-</td>");
            }

            html.append("</tr>");
        }

        html.append("</tbody></table></div>")
            .append("</main>")
            .append("<script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js'></script>")
            .append("<script>try{hljs.highlightAll();}catch(e){}</script>")
            .append("</body></html>");

        output.write(html.toString().getBytes(StandardCharsets.UTF_8));
        output.flush();
    }

    private static String escape(String s) {
        if (s == null) {
            return "";
        }
        return s.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&#39;");
    }
}
