plugins {
    id("io.micronaut.build.internal.json-schema-module")
}

dependencies {
    compileOnly(mn.micronaut.core.processor)

    implementation(mnSourcegen.micronaut.sourcegen.model)
    implementation(mnSourcegen.micronaut.sourcegen.generator)
    implementation(mnSourcegen.micronaut.sourcegen.generator.java)
    implementation(mnSourcegen.micronaut.sourcegen.annotations)
    implementation(mnSerde.micronaut.serde.jackson)

    compileOnly(mnBuildPluginSourcegen.micronaut.build.plugin.sourcegen.annotations)
    annotationProcessor(mnBuildPluginSourcegen.micronaut.build.plugin.sourcegen.generator)

    api(projects.micronautJsonSchemaAnnotations)
    api(projects.micronautJsonSchemaCommon)

    testAnnotationProcessor(mn.micronaut.inject.java)
    testImplementation(mn.micronaut.inject)
    testImplementation(libs.java.parser)
    testImplementation(mnValidation.micronaut.validation)
}

micronautBuild {
    descriptor {
        parentModuleId = "io.micronaut.jsonschema:micronaut-json-schema-generator"
    }
    binaryCompatibility.enabledAfter("2.0.0")
}
