import io.micronaut.testresources.buildtools.KnownModules

plugins {
    id("io.micronaut.build.internal.json-schema-module")
    id("io.micronaut.test-resources")
}

dependencies {
    compileOnly(mn.micronaut.core.processor)

    implementation(mnSourcegen.micronaut.sourcegen.model)
    implementation(mnSourcegen.micronaut.sourcegen.generator)
    implementation(mnSourcegen.micronaut.sourcegen.generator.java)
    implementation(mnSourcegen.micronaut.sourcegen.generator.kotlin)
    implementation(mnSourcegen.micronaut.sourcegen.annotations)
    implementation(mnSerde.micronaut.serde.jackson)

    api(projects.micronautJsonSchemaAnnotations)
    api(projects.micronautJsonSchemaCommon)

    testAnnotationProcessor(mn.micronaut.inject.java)
    testImplementation(mn.micronaut.inject)
    testImplementation(mn.micronaut.context)
    testImplementation(mnTestResources.testcontainers.oracle.free)
    testImplementation(mnTestResources.micronaut.test.resources.extensions.junit.platform)
    testImplementation(mn.java.parser.core)
    testImplementation(mnValidation.micronaut.validation)
    testRuntimeOnly(mnSql.ojdbc11)
    testResourcesService(mnSql.ojdbc11)
}

micronautBuild {
    descriptor {
        parentModuleId = "io.micronaut.jsonschema:micronaut-json-schema-generator"
    }
}

micronaut {
    version libs.versions.micronaut.platform.get()
    testResources {
        enabled = true
        inferClasspath = false
        additionalModules.add(KnownModules.JDBC_ORACLE_FREE)
        clientTimeout = 300
        version = libs.versions.micronaut.testresources.get()
    }
}
